ALTER TABLE courses
ADD COLUMN sessions_per_week INT NULL DEFAULT 2;

CREATE TABLE schedule_cancellations (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    class_id BIGINT NULL,
    reason NVARCHAR(255) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (class_id) REFERENCES classes(id) ON DELETE CASCADE
);
