package com.lms.education.module.user.service.impl;

import com.lms.education.exception.DuplicateResourceException;
import com.lms.education.exception.ResourceNotFoundException;
import com.lms.education.module.academic.repository.PhysicalClassRepository;
import com.lms.education.module.user.dto.StudentDto;
import com.lms.education.module.user.entity.Role;
import com.lms.education.module.user.entity.Student;
import com.lms.education.module.user.entity.User;
import com.lms.education.module.user.repository.RoleRepository;
import com.lms.education.module.user.repository.StudentRepository;
import com.lms.education.module.user.repository.UserRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.security.crypto.password.PasswordEncoder;

import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
public class StudentServiceImplTest {

    // KHAI BÁO CÁC DEPENDENCY DÙNG CHUNG (ĐƯỢC MOCK)
    @Mock
    private StudentRepository studentRepository;
    @Mock
    private UserRepository userRepository;
    @Mock
    private RoleRepository roleRepository;
    @Mock
    private PasswordEncoder passwordEncoder;
    @Mock
    private PhysicalClassRepository physicalClassRepository;

    @InjectMocks
    private StudentServiceImpl studentService;


    // NHÓM TEST 1: KIỂM THỬ CHỨC NĂNG TẠO TÀI KHOẢN CHO HỌC SINH ĐÃ TỒN TẠI
    @Nested
    class CreateAccountForExistingStudentTests {

        private Student mockStudent;
        private final String studentId = "student-123";

        @BeforeEach
        void setUp() {
            // Chuẩn bị dữ liệu mẫu trước mỗi Test Case trong nhóm này
            mockStudent = new Student();
            mockStudent.setId(studentId);
            mockStudent.setStudentCode("HS2024001");
        }

        @Test
        void createAccount_StudentNotFound_ShouldThrowException() {
            // Giả lập: Không tìm thấy học sinh trong DB
            when(studentRepository.findById(studentId)).thenReturn(Optional.empty());

            // Kì vọng hiển thị ra lỗi ResourceNotFoundException
            ResourceNotFoundException exception = assertThrows(ResourceNotFoundException.class, () -> {
                studentService.createAccountForExistingStudent(studentId, "test@gmail.com");
            });

            assertEquals("Học sinh không tồn tại", exception.getMessage());
        }

        @Test
        void createAccount_StudentAlreadyHasUser_ShouldThrowException() {
            // Giả lập: Học sinh đã được liên kết với một User từ trước
            mockStudent.setUser(new User());
            when(studentRepository.findById(studentId)).thenReturn(Optional.of(mockStudent));

            DuplicateResourceException exception = assertThrows(DuplicateResourceException.class, () -> {
                studentService.createAccountForExistingStudent(studentId, "test@gmail.com");
            });

            assertEquals("Học sinh này đã có tài khoản rồi!", exception.getMessage());
        }

        @Test
        void createAccount_AutoGeneratedEmailAlreadyExists_ShouldThrowException() {
            // Giả lập: Email tự động sinh (hs2024001@school.edu.vn) đã bị trùng
            when(studentRepository.findById(studentId)).thenReturn(Optional.of(mockStudent));
            String expectedGeneratedEmail = "hs2024001@school.edu.vn";
            when(userRepository.existsByEmail(expectedGeneratedEmail)).thenReturn(true);

            // truyền email null để kích hoạt nhánh tự động tạo email
            DuplicateResourceException exception = assertThrows(DuplicateResourceException.class, () -> {
                studentService.createAccountForExistingStudent(studentId, null);
            });

            assertTrue(exception.getMessage().contains("đã tồn tại trong hệ thống!"));
        }

        @Test
        void createAccount_RoleNotFound_ShouldThrowException() {
            // Giả lập: Database bị thiếu cấu hình Role STUDENT
            when(studentRepository.findById(studentId)).thenReturn(Optional.of(mockStudent));
            when(userRepository.existsByEmail(anyString())).thenReturn(false);
            when(passwordEncoder.encode(anyString())).thenReturn("hashed_password");

            // tìm Role trả về empty
            when(roleRepository.findByCode("STUDENT")).thenReturn(Optional.empty());

            RuntimeException exception = assertThrows(RuntimeException.class, () -> {
                studentService.createAccountForExistingStudent(studentId, "test@gmail.com");
            });

            assertEquals("Lỗi: DB thiếu role STUDENT", exception.getMessage());
        }

        @Test
        void createAccount_ValidData_ShouldCreateSuccessfully() {
            // Giả lập: Mọi điều kiện đều hợp lệ
            String inputEmail = "valid@gmail.com";
            Role mockRole = new Role();
            User mockSavedUser = new User();

            when(studentRepository.findById(studentId)).thenReturn(Optional.of(mockStudent));
            when(userRepository.existsByEmail(inputEmail)).thenReturn(false);
            when(passwordEncoder.encode(mockStudent.getStudentCode())).thenReturn("hashed_pw");
            when(roleRepository.findByCode("STUDENT")).thenReturn(Optional.of(mockRole));
            when(userRepository.save(any(User.class))).thenReturn(mockSavedUser);

            // Thực thi
            studentService.createAccountForExistingStudent(studentId, inputEmail);

            // luồng dữ liệu (White-box testing)
            verify(userRepository, times(1)).existsByEmail(inputEmail);
            verify(passwordEncoder, times(1)).encode("HS2024001");
            verify(userRepository, times(1)).save(any(User.class));
            verify(studentRepository, times(1)).save(mockStudent);

            assertEquals(mockSavedUser, mockStudent.getUser());
        }
    }

    // NHÓM TEST 2: KIỂM THỬ CHỨC NĂNG TẠO MỚI HỌC SINH (HÀM CREATE)
    @Nested
    class CreateStudentTests {

        private StudentDto inputDto;

        @BeforeEach
        void setUp() {
            // Chuẩn bị DTO giả lập
            inputDto = new StudentDto();
            inputDto.setStudentCode("HS2024002");
            inputDto.setFullName("Nguyen Van B");
        }

        @Test
        void createStudent_StudentCodeAlreadyExists_ShouldThrowException() {
            // Giả lập: Mã học sinh đã tồn tại trong DB
            when(studentRepository.existsByStudentCode("HS2024002")).thenReturn(true);

            DuplicateResourceException exception = assertThrows(DuplicateResourceException.class, () -> {
                studentService.create(inputDto);
            });

            assertEquals("Mã học sinh đã tồn tại: HS2024002", exception.getMessage());
            // Đảm bảo không có lệnh lưu dữ liệu nào được thực thi
            verify(studentRepository, never()).save(any(Student.class));
        }

        @Test
        void createStudent_ClassIdNotFound_ShouldThrowException() {
            // Giả lập: Mã học sinh hợp lệ, nhưng truyền ID Lớp học không có thực
            inputDto.setCurrentClassId("class-fake-id");
            when(studentRepository.existsByStudentCode("HS2024002")).thenReturn(false);
            when(physicalClassRepository.findById("class-fake-id")).thenReturn(Optional.empty());

            ResourceNotFoundException exception = assertThrows(ResourceNotFoundException.class, () -> {
                studentService.create(inputDto);
            });

            assertEquals("Lớp không tồn tại", exception.getMessage());
        }

        @Test
        void createStudent_ValidDataWithoutEmail_ShouldSaveStudentOnly() {
            // Giả lập: Dữ liệu hợp lệ, nhưng bỏ trống Email
            inputDto.setEmail(null);

            Student mockSavedStudent = new Student();
            mockSavedStudent.setId("new-student-id");
            mockSavedStudent.setStudentCode("HS2024002");

            when(studentRepository.existsByStudentCode("HS2024002")).thenReturn(false);
            when(studentRepository.save(any(Student.class))).thenReturn(mockSavedStudent);

            // Thực thi
            StudentDto result = studentService.create(inputDto);

            // Xác minh kết quả trả về
            assertNotNull(result);
            assertEquals("new-student-id", result.getId());

            // Xác minh luồng dữ liệu hộp trắng: KHÔNG GỌI lệnh tạo User vì không có email
            verify(userRepository, never()).existsByEmail(anyString());
            verify(userRepository, never()).save(any(User.class));
            // Đảm bảo lệnh lưu Student được gọi đúng 1 lần
            verify(studentRepository, times(1)).save(any(Student.class));
        }
    }
}